### ISSUE TITLE
I'd rather be using Framework XYZ for blogging, what gives?

### ISSUE THREAD

**Issue by jez** [ScottyLabs/blog#1]
_This is presented as an issue because I can't think of a better place to host this content. I don't think it belongs in the README, but it deserves being discussed. -- JZ_
## I'd rather be using Framework XYZ for blogging, what gives?

We've discussed having a ScottyLabs blog many times, and there has been some degree of interest, but ultimately no one stepped up. While there are many reasons for this, one of the most dividing issues is choosing a platform. The platform ScottyLabs uses for blogging should not be the limiting factor. In the Grand scheme of things, having a blog is much more important.

I looked into and tried out a number of blogging frameworks before finally settling on Ghost. If you had something in mind, see if it's mentioned explicitly below.
### Wordpress

WordPress is the most widely-used blogging platform. However, WordPress has become so large and complex that it's no longer a "blogging framework" as much of a CMS. There is a lot of cruft that comes along with running a whole CMS, which means that we'll be limited in our agility going forward. One good feature that WordPress does particularly well is managing multiple authors on the same blog.
### Medium

Medium has quickly risen to be the standard to beat when it comes to good blog design. Both their editing interface and reading view are simple, elegant and beautiful. However, Medium doesn't do collaboration well; it's centered around single-author posts. The reasoning for this is that Medium is actually more like a magazine. Instead of having one blog with multiple authors, there's Medium, which is a _huge_ blog with many, many authors.

Moreover, one of the biggest reasons why we need a blog is to increase visibility of our organization. One of the ways we should be doing this is by directing more traffic to our sites. On Medium, the impetus is to direct more traffic back to other Medium articles.
### Tumblr

Many people are familiar with Tumblr as a blogging platform. It lets you customize your theme really easily, it's free, and getting started with a new blog is really easy. However, Tumblr suffers from the same problem as Medium: managing multiple authors and editors is not possible. Of course, this isn't a problem for the single-user who wants to get started with a blog quickly, but it fails to scale well to an organization of bloggers.

On top of this, the Tumblr editing interface is terrible. Especially when judging it against Medium standards, the interface is incredibly lack-luster.  This is part of a larger problem that throughout Tumblr, the real emphasis is on consuming content rather than producing it. This makes sense: Tumblr is primarily a social media platform, aiming to connect people, rather than generate content.
### Ghost

When we consider all the benefits and faults of the systems above, Ghost possesses solutions that address many of them.

It's lighter-weight than Wordpress, but it still provides full support for multiple authors and editors. This means that two ScottyLabs members can log into Ghost and see their own content and their own drafts, not having to worry about messing up someone else's content or having their content messed up. On top of this, editors can come in and see all posts for reviewing them before they're ultimately published.

Moreover, the design is really nice, as the emphasis has been placed on generating content. The editing interface is great. It shows you both what the raw form of your post looks like as well as what it will look like when published. On top of this, we're getting started with a near-perfect Medium-clone theme, so the experience for our our readers will be just as elegant.

Ghost still has it's faults. First, creating new themes requires some knowledge of the terminal. Since we're hosting Ghost for ourself, you have to know your way around a terminal to get Ghost set up. However, in ScottyLabs we have plenty of people more than willing to get people up and running and help them learn what's required to create a theme.

Ghost also isn't completely stable yet. There are still features that are advertised as "Coming Soon." While we can't use these yet, the current state of the project, with the `ghost/` directory and the `ghost-override/` directory separated, will make upgrading Ghost in the future easy.
### Conclusion

If you feel particularly strongly against using Ghost, consider planning out an alternative solution thoroughly, being able identify and enumerate specific problems arising from the use of Ghost, and propose a platform that would solve these issues without introducing more problems in the process. Bring this up at or before a meeting and it will be discussed there.

Ultimately, none of the above blogging platforms are perfect, but that's because there isn't a perfect blogging platform. Ghost was chosen because it looks like the best long-term solution.

**Comment by bezi** [comment]
If we want to use Ghost, I'm wary.  It's a platform that few people (read: you and maybe Tom) know how to use.  It's cool, it's slick, it's the new hot thing, and I caution us using something that forces people to use the terminal to just use.  

I still believe Tumblr is the answer.  It's simple, ubiquitous, and I doubt that we'll be plowing out dozens of blog posts.  I'm pretty sure that what's going to happen is someone will be curating the blog and will be getting posts from the various authors that they will then upload.

Jake, your concerns against Tumblr are that its editing interface is 'terrible'.  I don't think we'll be writing blog posts online (Google Docs or personal editors as people are inclined, once again submitting it to whoever ends up being our content curator), and theming for Tumblr is widely known and such.  However, I feel like we need to bring this discussion to Scottylabs as a whole, as they will be the ones actually writing blog posts.  As the technical team, it is our responsibility to address the needs of the group as a whole, not do the cool new thing that is technically elegant and super nifty.  

Finally, what happened to the new members who were designers and were assigned to get a blog together?  We haven't given them a chance to weigh in on this.

What I propose: Put a discussion up in a Scottylabs meeting with both technical folks and designers, in a Google Hangout, especially with Taylor, Tom, and the people who were looking into the blogs present.  I would also like to be involved with this.  If I don't hear any objections in the next 24 hours I'll go forth and set that up.

**Comment by tomshen** [comment]
With regards to Ghost, the actual editing interface is a very straightforward Markdown editor:

![image](https://cloud.githubusercontent.com/assets/2065456/5571834/7d6c92d6-8f64-11e4-8fdd-0cfc9fada557.png)

with mobile support:
![image](https://cloud.githubusercontent.com/assets/2065456/5571864/d7840fce-8f64-11e4-91eb-55aa17d1bea0.png)

This is super easy to use for technical people who write Markdown all the time. However, nontechnical people may not want to learn Markdown. It does **not** require using the terminal to write posts though.

I don't think support for multiple users that important. We can all just share one account, and add a byline to each post.

Wordpress and Tumblr are popular and familiar, but force us to relinquish control of blog server. I'd rather self-host, but if that's what the people actually editing/designing the blog want, I have no issue with either.

**Comment by jez** [comment]
Cool. I have no connection right now, and I have some thoughts that I'd
really like to bring up. Can we postpone further discussion until after New
Year's?

**Comment by tomshen** [comment]
Yup, I just wanted to get some of my thoughts out there. Let's discuss this at the post-New Year's meeting.

**Comment by jez** [comment]
Sounds like we decided on Medium. Maybe eventually we'll write some posts.
